### ISSUE TITLE
Remove the word "member"

### ISSUE THREAD

**Issue by Gianni-Pucillo** [eclipse-che4z/che-che4z-zos-resource-explorer#32]
**Description**:
Remove the word "member" from the following actions:

1. browse member
2. edit member
3. delete member

**Note**:
Do NOT remove from "create member". This action stays as is so that the user knows he is creating new member and not a new dataset

**Acceptance criteria**:
browse, edit and delete actions are without the word "member"

ID: US611142

**Comment by shciubrcom** [comment]
I think we should update also command ids.

**Comment by Gianni-Pucillo** [comment]
Can I do it right now?

Furthermore what 'ids' means exactly? the word 'memeber' that is attached to the commands inside package.json?

Please confirm just to be sure.

**Comment by shciubrcom** [comment]
Each command has its identification string. It declared in package.json and used in source code and in package.json.
