### ISSUE TITLE
Which port to use

### ISSUE THREAD

**Issue by Morridt** [eclipse-che4z/che-che4z-zos-resource-explorer#85]
Instructions request entering a host and port but is not clear on what it is trying to connect to in backend.  Have tried our z/OSMF host:port which works for Zowe but still comes up with Host is not available.

**Comment by shciubrcom** [comment]
Currently, Explorer for z/OS uses [Explorer Data Sets API](https://github.com/zowe/data-sets) to access to the mainframe. You can start instance of it locally. There is [documentation](https://github.com/zowe/data-sets/blob/master/README.md) how to set it up.
1. Download and build data-set server.
2. Generate test certificate.
3. Start test server with your z/OSMF host:port.
